; OnePress
#Include blank-share\blank-share.ahk
#Include payment-relation\payment-relation.ahk
#Include group-share-dnm\group-share-dnm.ahk
#Include cashiering\cashiering.ahk
#Include batch-keys\batch-keys-xl.ahk
#Include batch-keys\batch-keys-sq.ahk
#Include fetch-fedex-resv\fetch-fedex-resv.ahk
#Include rate-checking\rate-checking.ahk